Update tests_coverage.yml

diff --git a/.github/workflows/tests_coverage.yml b/.github/workflows/tests_coverage.yml
--- a/.github/workflows/tests_coverage.yml
+++ b/.github/workflows/tests_coverage.yml
@@ -40,34 +40,40 @@ jobs:
 
       - name: Build Maven
         run: mvn clean install
-
-      - name: Setup Pages
-        uses: actions/configure-pages@v3
-
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v1
+        
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
         with:
-          path: "coverage/target/site/jacoco-aggregate/"
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v2
-
-      ##### Added #####
-      - name: Commit and Push to History Branch
-        run: |
-          git fetch
-          git branch -a
-          git checkout -- .
-          git checkout -b history_reports origin/history_reports
-          git config --global user.email "mathilde.marza2001@gmail.com"
-          git config --global user.name "MathildeMrz"
-          # git pull origin develop
-          git add -f "coverage/target/site/jacoco-aggregate/"
-          DATE=$(date +%Y-%m-%d-%H-%M-%S)
-          mkdir -p history/"$DATE"
-          cp -R "coverage/target/site/jacoco-aggregate/." history/"$DATE"/
-          git add -f history/"$DATE"
-          git commit -m "Update Jacoco HTML report"
-          git push origin
-          # git push develop history_reports
+#      - name: Setup Pages
+#        uses: actions/configure-pages@v3
+#
+#      - name: Upload artifact
+#        uses: actions/upload-pages-artifact@v1
+#        with:
+#          path: "coverage/target/site/jacoco-aggregate/"
+#
+#      - name: Deploy to GitHub Pages
+#        id: deployment
+#        uses: actions/deploy-pages@v2
+#
+#      ##### Added #####
+#      - name: Commit and Push to History Branch
+#        run: |
+#          git fetch
+#          git branch -a
+#          git checkout -- .
+#          git checkout -b history_reports origin/history_reports
+#          git config --global user.email "mathilde.marza2001@gmail.com"
+#          git config --global user.name "MathildeMrz"
+#          # git pull origin develop
+#          git add -f "coverage/target/site/jacoco-aggregate/"
+#          DATE=$(date +%Y-%m-%d-%H-%M-%S)
+#          mkdir -p history/"$DATE"
+#          cp -R "coverage/target/site/jacoco-aggregate/." history/"$DATE"/
+#          git add -f history/"$DATE"
+#          git commit -m "Update Jacoco HTML report"
+#          git push origin
+#          # git push develop history_reports
